version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: cscrf
      POSTGRES_PASSWORD: changeMe!
      POSTGRES_DB: cscrf_db

  redis:
    image: redis:alpine
